<div>
    <form id="ui-config-form">
        <fieldset>
            <legend>模型名称:</legend>
            <input name="name" type="text">
        </fieldset>

        <fieldset>
            <legend>选择数据源:</legend>

            <div>
                <select name="source"></select>
            </div>
        </fieldset>

        <fieldset>
            <legend>数据查询规则:</legend>

            <table id="ui-config-columns">
                <thead>
                <tr>
                    <th>排序</th>
                    <th>字段名</th>
                    <th>隐藏显示</th>
                    <th>显示名称</th>
                    <th>显示模板</th>
                    <th>定宽</th>
                    <th>字段排序</th>
                    <th>过滤器</th>
                    <th>类型</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </fieldset>

        <fieldset>
            <legend>明细视图:</legend>

            <div>
                <button value="table"> 表格 </button>
                <textarea name="detail_template" style="width: 100%;" rows="10"
                          id="ui-config-detail-template"></textarea>
            </div>
        </fieldset>

        <button type="submit">提交</button>
    </form>
</div>

<script id="ui-config-column-config-template" type="text/kendo-ui-template">
    <tr>
        <td><button type="button" data-action="up">↑</button>  <button type="button" data-action="down">↓</button></td>
        <td>#:item.field#<input type="hidden" name="columns[field][#:item.field#]" value="#:item.field#"></td>
        <td><input type="checkbox" name="columns[hidden][#:item.field#]" value="1"></td>
        <td><input type="text" name="columns[title][#:item.field#]" value=""></td>
        <td><input type="text" name="columns[template][#:item.field#]" value=""></td>
        <td><input type="number" step="10" name="columns[width][#:item.field#]" value=""></td>
        <td><input type="checkbox" name="columns[sortable][#:item.field#]" value="1"></td>
        <td><input type="checkbox" name="columns[filterable][#:item.field#]" value="1"></td>
        <td><select></select></td>
    </tr>
</script>

<script>
    $(function () {

         var $selectSource = $("#ui-config-form select[name=source]"),
            $columnsConfigTbody = $('#ui-config-columns tbody'),
            $detailTemplate = $('#ui-config-detail-template'),
            $uiConfigForm = $('#ui-config-form'),
            kColumnTemplate = kendo.template($('#ui-config-column-config-template').html());

        $columnsConfigTbody.bind('init', function (e, fields) {
            $columnsConfigTbody.empty();
            $.each(fields, function (field, o) {
                $columnsConfigTbody.append(kColumnTemplate({item: {field: field}}));
            });
        });
        $selectSource.bind('init', function (e, sources) {
            $(this).empty().append('<option value=""> -- 选择数据源 --</option>');

            $.each(sources, function (i, item) {
                $('<option value="' + item.name + '">' + item.name + '</option>').data('fields', item.fields).appendTo($selectSource);
            });
        });

        //数据源选择
        $selectSource.change(function () {
            if (!$selectSource.val()) {
                return;
            }

            var fields = $('option:selected', this).data('fields');
            $columnsConfigTbody.trigger('init', [fields]);
        });

        $columnsConfigTbody.on('click', 'tr td button', function () {
            var row = $(this).closest('tr');
            if ($(this).data('action') == 'up') {
                if (row.prev().size()) {
                    row.prev().before(row);
                }
            } else {
                if (row.next().size()) {
                    row.next().after(row);
                }
            }
        });

        $.get(
            '<?=$this->url('zfegg-model-manager/params', ['controller' => 'ui-config', 'action' => 'init'])?>',
            function (r) {
                $selectSource.trigger('init', [r.data_source]);
            }
        );

        $('#ui-config-form button[value=table]').click(function (e) {
            var $tmpl = $('<table></table>');

            $selectSource.val();
            $columnsConfigTbody.children().each(function () {
                var $filed = $('input[name^="columns[field]"]', this);
                if ($filed.size()) {
                    var title = $('input[name^="columns[title]"]', this).val() || $filed.val();
                    $tmpl.append('<tr><td>' + title + '</td><td>#:' + $filed.val() + '#</td></tr>');
                }
            });
            $detailTemplate.val($tmpl.get(0).outerHTML);
        });

        $uiConfigForm.submit(function (e) {
            e.preventDefault();

            $.post(
                './model-manager/ui-config/save',
                $(this).serialize(),
                function (r) {
                    alert('添加成功');
                }
            );
        });

    });
</script>